trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TriggerAnotherPipeline
  steps:
    - bash: |
        echo "Triggering another pipeline..."
        curl -u :$(System.AccessToken) -X POST \
        -H "Content-Type: application/json" \
        --data '{"resources": {"repositories": {"self": {"refName": "refs/heads/main"}}}}' \
        https://dev.azure.com/PedroPereira0371/BookNest/_apis/pipelines/21/runs?api-version=6.0-preview.1
      env:
        System.AccessToken: $(System.AccessToken)
      displayName: 'Trigger another pipeline'
